rails:
  build: .
  command: ./dev.sh
  volumes:
    - .:/app
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    DATABASE_HOST: db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: db

bundle:
  image: busybox
  volumes:
    - /bundle

db:
  image: postgres:9.6
  ports:
    - "15432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
